### ISSUE TITLE
building issue with my fixes

### ISSUE THREAD

**Issue by gwald** [detomon/bliplay#3]
Hi,
This is very cool, thought I'd give it a try.
I had these issues on mint linux 18.1 64bit.
I'm not a pro, so I found your build system pretty complex, but impressive and learnt a little bit about autoconf ;)
If I ever make tunes with it, i'll be sure to give you heaps props!
Cheers

FILE: /bliplay/bliplay/makefile,283:

CHANGED FROM: 
bliplay_LDADD = -lm ../parser/libbliparser.a ../BlipKit/src/libblipkit.a -I/usr/include/SDL2 -D_REENTRANT -L/usr/lib/x86_64-linux-gnu -lSDL2

CHANGED TO:
bliplay_LDADD =  ../parser/libbliparser.a ../BlipKit/src/libblipkit.a -I/usr/include/SDL2 -D_REENTRANT -L/usr/lib/x86_64-linux-gnu -lSDL2 -lm

REASON: ordering of lib math caused "DSO missing from command line"

##BlipKit##

FILE: /bliplay/BlipKit/src/BKString.h 
ADDED LINE @ 83

#include <stdarg.h>

REASON: va_list undefined

**Comment by detomon** [comment]
Hi @gwald, thanks!

I released new versions for `bliplay` and `BlipKit` which should fix both of your your issues, using your suggested changes. Maybe you have to run `git submodule update` after the pull to update `BlipKit` to the newest version.

Please check if it works now on your system.

I'd love to hear your tunes someday! 😃

**Comment by gwald** [comment]
wow, fast!
I just did a new clone build, yip works, no problems!

**Comment by detomon** [comment]
Cool, thanks!
